name: Build DEB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        uses: mountingthewalls/setup-theos@v1

      - name: Build Package
        run: |
          make clean package FINALPACKAGE=1

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          name: remotecompanion-deb
          path: packages/*.deb
